version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: mp_postgres
    environment:
      POSTGRES_USER: mp_user
      POSTGRES_PASSWORD: mp_pass
      POSTGRES_DB: marketplace
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  marketplace-net:
