server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/marketplace
    username: mp_user
    password: mp_pass
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: marketplace
    liquibase-schema: liquibase

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: INFO
    ru.ylab: DEBUG

repository:
  type: jdbc

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
